import joi from "joi";

const colorPalette = joi
  .object({
    0: joi.string().required(),
    5: joi.string().required(),
    10: joi.string().required(),
    15: joi.string().required(),
    20: joi.string().required(),
    25: joi.string().required(),
    30: joi.string().required(),
    35: joi.string().required(),
    40: joi.string().required(),
    50: joi.string().required(),
    60: joi.string().required(),
    70: joi.string().required(),
    80: joi.string().required(),
    90: joi.string().required(),
    95: joi.string().required(),
    98: joi.string().required(),
    99: joi.string().required(),
    100: joi.string().required(),
  })
  .required();

const sysBaseSchema = joi.object({
  primary: joi.string().required(),
  onPrimary: joi.string().required(),
  primaryContainer: joi.string().required(),
  onPrimaryContainer: joi.string().required(),
  primaryFixed: joi.string().required(),
  onPrimaryFixed: joi.string().required(),
  primaryFixedDim: joi.string().required(),
  onPrimaryFixedVariant: joi.string().required(),
  secondary: joi.string().required(),
  onSecondary: joi.string().required(),
  secondaryContainer: joi.string().required(),
  onSecondaryContainer: joi.string().required(),
  secondaryFixed: joi.string().required(),
  onSecondaryFixed: joi.string().required(),
  secondaryFixedDim: joi.string().required(),
  onSecondaryFixedVariant: joi.string().required(),
  tertiary: joi.string().required(),
  onTertiary: joi.string().required(),
  tertiaryContainer: joi.string().required(),
  onTertiaryContainer: joi.string().required(),
  tertiaryFixed: joi.string().required(),
  onTertiaryFixed: joi.string().required(),
  tertiaryFixedDim: joi.string().required(),
  onTertiaryFixedVariant: joi.string().required(),
  error: joi.string().required(),
  onError: joi.string().required(),
  errorContainer: joi.string().required(),
  onErrorContainer: joi.string().required(),
  outline: joi.string().required(),
  background: joi.string().required(),
  onBackground: joi.string().required(),
  surface: joi.string().required(),
  onSurface: joi.string().required(),
  surfaceVariant: joi.string().required(),
  onSurfaceVariant: joi.string().required(),
  inverseSurface: joi.string().required(),
  inverseOnSurface: joi.string().required(),
  inversePrimary: joi.string().required(),
  shadow: joi.string().required(),
  surfaceTint: joi.string().required(),
  outlineVariant: joi.string().required(),
  scrim: joi.string().required(),
  surfaceContainerHighest: joi.string().required(),
  surfaceContainerHigh: joi.string().required(),
  surfaceContainer: joi.string().required(),
  surfaceContainerLow: joi.string().required(),
  surfaceContainerLowest: joi.string().required(),
  surfaceBright: joi.string().required(),
  surfaceDim: joi.string().required(),
});

// Figma "Material Theme Builder" plugin export output schema
export const md3ThemeSchema = joi.object({
  seed: joi.string(),
  name: joi.string(),
  description: joi.string(),
  coreColors: joi
    .object({
      primary: joi.string().required(),
      secondary: joi.string().required(),
      neutral: joi.string().required(),
      neutralVariant: joi.string().required(),
    })
    .required(),
  schemes: joi.object({
    light: sysBaseSchema,
    dark: sysBaseSchema,
  }),
  palettes: joi.object({
    primary: colorPalette,
    secondary: colorPalette,
    tertiary: colorPalette,
    error: colorPalette,
    neutral: colorPalette,
    neutralVariant: colorPalette,
  }),
  styles: joi.object(),
  extendedColors: joi.array(),
});
